### ISSUE TITLE
Wordpress keeps warning me every time I create a new service:

### ISSUE THREAD

**Issue by alessandraurso** [damanic/mjm-clinic#3]
"Warning: Declaration of MJM_Walker_SlugValueCategoryDropdown::start_el(&$output, $category, $depth, $args) should be compatible with Walker_CategoryDropdown::start_el(&$output, $category, $depth = 0, $args = Array, $id = 0) in /homepages/0/d641402561/htdocs/app641435756/wp-content/plugins/mjm-clinic/class-misc.php on line 0"

**Comment by damanic** [comment]
thanks
